- name: "Disabling default NodeJS version"
  ansible.builtin.command: "dnf module disable nodejs -y"

- name: "enabling NodeJS version:20"
  ansible.builtin.command: "dnf module enable nodejs:20 -y"

- name: "Installing Nodejs and Mysql"
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  loop:
    - nodejs
    - mysql

- name: "Installing packages"
  ansible.builtin.pip:
    name: "{{ item }}"
    state: present
    executable: pip3.9
  loop:
    - PyMySQL
    - cryptography

- name: "Download backend files"
  ansible.builtin.get_url:
    url: https://expense-builds.s3.us-east-1.amazonaws.com/expense-backend-v2.zip
    dest: /tmp/backend.zip

- name: "Creating directory /app"
  ansible.builtin.file:
    state: directory
    path: /app

- name: "Unzip the code in /app"
  ansible.builtin.unarchive:
    src: /tmp/backend.zip
    dest: /app
    remote_src: yes

- name: "Installing dependencies of package.json"
  ansible.builtin.npm:
    path: /app

- name: "configuring backend as service"
  ansible.builtin.template:
    src: backend.service.j2
    dest: /etc/systemd/system/backend.service

- name: "Starting and enabling backend"
  ansible.builtin.service:
    name: backend
    enabled: yes
    daemon-reload: true
    state: started

- name: "Creating expense user"
  ansible.builtin.user:
    user: expense

- name: "Loading schema"
  community.mysql.mysql_db:
    name: all
    state: import
    login_user: root
    login_password: ExpenseApp@1
    login_host: database.vijaydev.space
    target: /app/schema/backend.sql

- name: "restarting and enabling backend"
  ansible.builtin.service:
    name: backend
    daemon-reload: true
    state: restarted


