- name: "Disabling default NodeJS version"
  ansible.builtin.command: "dnf module disable nodejs -y"

- name: "enabling NodeJS version:20"
  ansible.builtin.command: "dnf module enable nodejs:20 -y"

- name: "Installing Nodejs and Mysql"
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  loop:
    - nodejs
    - mysql

- name: "Installing packages"
  ansible.builtin.pip:
    name: "{{ item }}"
    state: present
    executable: pip3.9
  loop:
    - PyMySQL
    - cryptography

- name: "Importing common role for Downloading the file and placing in /app directory"
  # tags:
  #   - deployment
  ansible.builtin.include_role:
    name: common
    tasks_from: main

# - name: "Download backend files"
#   ansible.builtin.get_url:
#     url: https://expense-builds.s3.us-east-1.amazonaws.com/expense-backend-v2.zip
#     dest: /tmp/backend.zip

# - name: "Creating directory /app"
#   ansible.builtin.file:
#     state: directory
#     path: /app

# - name: "Unzip the code in /app"
#   ansible.builtin.unarchive:
#     src: /tmp/backend.zip
#     dest: /app
#     remote_src: yes

- name: "Installing dependencies of package.json"
  ansible.builtin.npm:
    path: /app

# - name: "configuring backend as service"
#   ansible.builtin.copy: #Here if we use copy module then src will refer files
#     src: backend.service 
#     dest: /etc/systemd/system/backend.service

- name: "configuring backend as service"
  ansible.builtin.template:
    src: backend.service.j2 #Here if we use template module then src will refer template
    dest: /etc/systemd/system/backend.service
  notify: #Notify when some change event happened and redirect to handler and execute the handler
    - Starting and enabling backend

- name: "Creating expense user"
  ansible.builtin.user:
    user: expense

- name: "Loading schema"
  community.mysql.mysql_db:
    name: all
    state: import
    login_user: "{{ MYSQL_USER }}"
    login_password: "{{ MYSQL_PASSWORD }}"
    login_host: "{{ MYSQL_HOST }}"
    target: /app/schema/backend.sql

- name: "restarting and enabling backend"
  tags:
    - deployment
  ansible.builtin.service:
    name: backend
    daemon-reload: true
    state: restarted


