- name: "Installing mysql-server"
  ansible.builtin.package:
  name: mysql-server
  state: present

- name: "Installing mysql-server"
  ansible.builtin.service:
  name: mysqld
  enabled: yes
  state: start

- name: "Login to database using root password"
  community.mysql.mysql_info:
  login_user: root
  login_password: "{{ mysql_password }}"
  login_host: database.vijaydev.space
  ignore_errors: true
  registers: mysql_info

- name: "Setting up root password to database"
  ansible.builtin.command: mysql_secure_installation --set-root-pass {{ mysql_rootpasswd }}
  when: mysql_info.failed is true




  

